# -*- coding: utf-8 -*-
"""summary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUyEGX2P81e9otYMbSjY_uSne3PhsoXe
"""

# !pip install transformers

import torch
from transformers import PreTrainedTokenizerFast
from transformers import BartForConditionalGeneration

tokenizer = PreTrainedTokenizerFast.from_pretrained("ainize/kobart-news")
# Encode Input Text

"""## 모델로드 """

model = BartForConditionalGeneration.from_pretrained("ainize/kobart-news")

input_text = '''
랜덤이라니요 이제품의 특징은 빛이나오는 스위치부분이 흰거 라면서요! 눈이피로하지 않은 스위치라고 자랑해놓고 주황스위치 보내시네요. 그외에는 일반적인 멀티탭과 같구요.  
전원이 오버되면 전원이 차단되는 검정스위치가 부착되어 있습니다. 어떤 전열 기기가 몇 와트인지 봉투에 기입이 되어있어요. 안전캡 2개 들었습니다. 최대 6구. 3미터 멀티탭 
전체 스위치를 관리하는 총괄스위치는 없어요. 소비전력 합 최대 2,800W까지 사용이라 해놓고,반드시70% 인 1,900W를 넘지않게 사용하라고 하네요. (또한번 윙??) 
스위치 색상 흰거 안와요. 주황스위치 옵니다. 중국산입니다. 재고부족으로 주황스위치 랜덤으로 옵니다.작은아이 방에 컴 관련코드가 많아서 멀티탭을 사용중 이었어요. 
하지만 오래써서 인지 며칠전 서랍장 갈아주다가 우연히 흔들어보니 달그락달그락 소리가 나는겁니다. 한달전쯤 큰아이가 망가진줄 모르고 사용하던 멀티탭에 노트북 스위치 꽂다가 
뻥터져서 손끝에 까맣게 그을음 생기고 연기나고 놀란적 있어서, 이번에는 언능 새 멀티탭을 구매 했습니다.  
포장지 다 뜯고 설치 해 줬는데 뭔가 이상해서보니 구매 했을때 설명에 있던 깨끗한 느낌이 없는거에요.  으잉?? 스위치 부분이 하얀색이라서 구매한건데 주황이 왔고, 
자재수급부족으로 색상을 구형과 랜덤발송 한다고 설명에 있네요. 뭔가 낚인느낌!! 주황불은 밤에 눈부셔서 불투명 흰스위치가 필요했거든요.  
아.. 제가 자세히 못본것도 있지만 후기에도 맨윗줄 나온거는 전부 흰스위치던데 부랴부랴 최근후기 찾아보니 요즘꺼는 모두 주황스위치고, 이러실꺼면 랜덤발송이 아니라 당분간 그냥 주황스위치 
보내는걸로 사진 바꿔주세요.  뭐가 급했나 국내산 제품도 똑같은 사양 1,000원 밖에 차이 안나는데 6구 짜리라는것과 다른설명  확인하느라 중국산인것을 간과 했어요.   
저는 별점 3개 드리겠습니다. 아 짜증나!!!!!!!!!!   **구매에 도움이 되셨길 바랍니다**
'''
input_ids = tokenizer.encode(input_text, return_tensors="pt")

summary_text_ids = model.generate(
    input_ids=input_ids,
    bos_token_id=model.config.bos_token_id,
    eos_token_id=model.config.eos_token_id,
    length_penalty=2.0,
    max_length=50,
    min_length=30,
    num_beams=4,
)

print(tokenizer.decode(summary_text_ids[0], skip_special_tokens=True))

